### ISSUE TITLE
Can not run soap server using document-style binding

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-soap#11]
I'm trying to use document-style binding startegy with following test code:

```
<?php
include '../vendor/autoload.php';

ini_set("soap.wsdl_cache_enabled", "0");

class MyClass {
	/**
	 * @param string $inputParam
	 * @param string $inputParam2
	 * @return string
	 */
    public function method1($inputParam, $inputParam2) {
        return "$inputParam $inputParam2";
    }
}

if ($_SERVER['REQUEST_METHOD'] == 'GET') {
    if (isset($_GET['wsdl'])) {
		// WSDL code
		$autodiscover = new Zend\Soap\AutoDiscover();
		$autodiscover
			->setBindingStyle([
				'style' => 'document',
			])
			->setClass('MyClass')
			->setUri('http://localhost.loc/test.php');
		header('Content-Type: text/xml');
		echo $autodiscover->toXml();
	} else {
		// Client code
		$client = new Zend\Soap\Client('http://localhost/test.php?wsdl');
		print_r($client->method1(22, 'some string'));
	}
} else {
	// Server code
	$soap = new Zend\Soap\Server("http://localhost/test.php?wsdl");
	$soap->setClass('MyClass');
	$soap->handle();
}

```

But when I try to run this script I get error:

> SoapFault: Error cannot find parameter in C:\usr\work\amayama\amayama-eng\vendor\zendframework\zend-soap\src\Client.php on line 1166

If I remove the binding style config - it work fine. What I do wrong?

---

Originally posted by @speller at https://github.com/zendframework/zend-soap/issues/43

**Comment by rdoering** [comment]
Is it possible, that this is an PHP-soapServer issue?

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you need an actively developed SOAP client, we recommend [phpro/soap-client](https://github.com/phpro/soap-client).
