### ISSUE TITLE
Soapenv:Header in request

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-soap#2]
Is there a way to accept soapenv:Header data in a request to a soap server?

We are receiving an header data and the server is returning an error because of this header.

`<soapenv:Header> <esb:header> <esb:message_type>AddNewOrder</esb:message_type> <esb:version>01.80</esb:version> <esb:source_entity>LPRO</esb:source_entity> <esb:source_application>NOLS</esb:source_application> <esb:destination_entity>KEIT</esb:destination_entity> <esb:destination_application>TIRE</esb:destination_application> </esb:header> </soapenv:Header>`

Do we need to define it in the wsdls and if yes how can we do that as we are not able to find it in the documentation.

---

Originally posted by @hypemedia at https://github.com/zendframework/zend-soap/issues/60

**Comment by mostafaznv** [comment]
I have this question too

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you need an actively developed SOAP client, we recommend [phpro/soap-client](https://github.com/phpro/soap-client).
