### ISSUE TITLE
Soap\Server::handle() never returns

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-soap#20]
Hi There,

I'm having a problem when using Soap\Server() but I'm not 100% sure if this is a framework bug or if I'm not using the API correctly (as the documentation is a little sparse on the matter)

If I construct Soap\Server() with WSDL generated from Soap\AutoDiscover->generate(), a very strange thing happens. Upon calling Server->handle(), the framework will bail **immediately** and _prints_ the following (regardless of ::setReturnResponse) :

```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Body>
        <SOAP-ENV:Fault>
            <faultcode>SOAP-ENV:Server</faultcode>
            <faultstring>SoapServer::SoapServer(): Invalid parameters</faultstring>
        </SOAP-ENV:Fault>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

In addition, _anything_ outputted previously will appear inside a "detail" element appended to the "Fault" element.

What could be causing this?

I look forward to your thoughts. Thanks in advance.

PS I notice there are no bugs here, should I be making this bug somewhere else?

---

Originally posted by @feamsr00 at https://github.com/zendframework/zend-soap/issues/6

**Comment by weierophinney** [comment]
Note: If I instead consume the WSDL from a _second_ request to the echoed XML (eg "../Service?wsdl") it works. But, this couldn't be by design. Having to spin up full tcp\httpd\php\framework machinery just to get at data that is a few JMPs away is ludicrous, right?


---

Originally posted by @feamsr00 at https://github.com/zendframework/zend-soap/issues/6#issuecomment-167297445

**Comment by weierophinney** [comment]
Giving this issue a bump, was setting up a SOAP integration but ran into this issue which is now rather blocking.

---

Originally posted by @ghost at https://github.com/zendframework/zend-soap/issues/6#issuecomment-366227001

**Comment by SalvatorePollaci** [comment]
UP

**Comment by Xerkus** [comment]
Proper way to bump the issue is by opening the PR

**Comment by weierophinney** [comment]
@SalvatorePollaci Or by providing information on how to reproduce.

There's no information here on how the author was setting up the Autodiscover or Server instances, or what types of classes or functions were being attached; it's entirely possible there are errors.

Based on the comments they posted later, it sounds very much like they could be calling code that has side effects in terms of output that would cause the instances to raise error conditions.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> If you need an actively developed SOAP client, we recommend [phpro/soap-client](https://github.com/phpro/soap-client).
