### ISSUE TITLE
Sipport ci in travis on GIthub Actions

### ISSUE THREAD

**Issue by Smolevich** [laminas/laminas-soap#21]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

Now main ci run in travis and only docs- build run on Github Actions.
Do you have plans to migrate travis ci plan to Github Actions or replace travis on GA ?

**Comment by michalbundyra** [comment]
@Smolevich This is not related to the component. We are doing it for all components.

We are not planning migration to Github Actions, at least for now.
Why are you asking? What benefits of the migration you see?

**Comment by Smolevich** [comment]
> @Smolevich This is not related to the component. We are doing it for all components.
> 
> We are not planning migration to Github Actions, at least for now.
> Why are you asking? What benefits of the migration you see?

1. For most cases FA faster and more stable than travis
2. GA is component inside Github
3. More flexible that travis, you can create custom private and public actions and use in many projects
