### ISSUE TITLE
PHP 8.2 error: Callables of the form `["Laminas\Soap\Client\Common", "SoapClient::__doRequest"]` are deprecated

### ISSUE THREAD

**Issue by Slamdunk** [laminas/laminas-soap#38]
```php
Code     E_DEPRECATED
Message  Callables of the form ["Laminas\Soap\Client\Common", "SoapClient::__doRequest"] are deprecated
File     ./vendor/laminas/laminas-soap/src/Client.php:1084
```

This hasn't been caught in https://github.com/laminas/laminas-soap/pull/34 because `\Laminas\Soap\Client::_doRequest` isn't covered

**Comment by Slamdunk** [comment]
@froschdesign you were kind enough to let me open a PR for this, but I guess I'll need to move to another library before `PHP 8.3`, am I correct?

**Comment by froschdesign** [comment]
@Slamdunk 
This component is in security-only maintenance mode and this means:

- it will get updates to support PHP 8.3
- most bug fixes are adopted and released
- you can take on the role of maintainer by [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
- or look at an alternative package like [phpro/soap-client](https://github.com/phpro/soap-client)
